services:
 
  postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      DATABASE_HOST: localhost
      POSTGRES_USER: roberto
      POSTGRES_PASSWORD: roberto123
      POSTGRES_DB: sistema_contable
 
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "roberto@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "rober123"
    ports:
      - "80:80"
    depends_on:
      - postgres
 
 